applications:
  app:
    source:
      root: /
    
    type: 'php:8.3'
    
    dependencies:
      php:
        composer/composer: '^2'
    
    runtime:
      extensions:
        - mbstring
    
    web:
      upstream:
        socket_family: tcp
        protocol: http
      commands:
        start: |
          PORT=$PORT ./pasir --port $PORT
      locations:
        '/':
          passthru: true
          root: 'public'
          index:
            - index.php
    
    hooks:
      build: |
        set -e
        echo "Installing Symfony dependencies..."
        composer install --no-dev --optimize-autoloader
        chmod +x pasir
        
      deploy: |
        set -e
        echo "Deployment complete!"
    
    variables:
      env:
        APP_ENV: 'prod'
    
    mounts:
      '/var':
        source: tmp
        source_path: var
